-- Brief 3: per-user inventory + scan metering (Neon Postgres).
-- Run AFTER the Better Auth tables exist (those are generated by
--   npx @better-auth/cli@latest generate   → db/schema_auth.sql
-- and applied first, because the FKs below reference "user"(id)).
--
-- Apply: paste into the Neon SQL editor, or
--   node --env-file=.env.local db/migrate.mjs   (after pulling env)

-- One row per comic, scoped to its owner. Rich fields live in `data` (jsonb);
-- the promoted columns are the ones we query / report on.
CREATE TABLE IF NOT EXISTS inventory (
  id             BIGSERIAL PRIMARY KEY,
  user_id        TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  client_id      TEXT,                       -- the comic.id from the client (for upsert/dedup)
  title          TEXT,
  issue          TEXT,
  publisher      TEXT,
  year           TEXT,
  condition      TEXT,
  grade          TEXT,
  purchase_price NUMERIC,
  est_value      NUMERIC,
  data           JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, client_id)
);
CREATE INDEX IF NOT EXISTS idx_inventory_user ON inventory (user_id);

-- Monthly scan counter, one row per user per 'YYYY-MM'. Incremented atomically
-- by the scan route; quota by tier is enforced server-side.
CREATE TABLE IF NOT EXISTS usage (
  user_id    TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  period     TEXT NOT NULL,                  -- 'YYYY-MM'
  scans_used INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, period)
);
